services:
  db:
    image: timescale/timescaledb:2.11.1-pg14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/nginx/challenges:/var/www/challenges
      - ./volumes/static:/static
      - ./volumes/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp

#  certs:
#    image: certbot/certbot
#    container_name: certs
#    restart: "no"
#    volumes:
#      - ./volumes/certs:/etc/letsencrypt
#      - ./volumes/nginx/challenges:/var/www/challenges
#    command: >
#      sh -c "trap exit TERM; while :; do certbot renew && sleep 12h & wait $${!}; done;"
#    depends_on:
#      - nginx

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: project.settings
    env_file:
      - .env
    volumes:
      - .:/app
      - ./volumes/static:/app/static
    depends_on:
      - db

volumes:
  postgres:
  nginx:
  static:
  certs:
