services:
  db:
    image: timescale/timescaledb:2.11.1-pg14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/staticfiles
    depends_on:
      - webapp
    networks:
      - frontend
    ports:
      - "80:80"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: project.settings
    env_file:
      - .env
    volumes:
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    networks:
      - backend
      - frontend

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - backend

volumes:
  postgres:
  staticfiles:

networks:
  backend:
  frontend:
