# Generated by Django 5.1.3 on 2025-05-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['sensor', 'timestamp'], name='core_datapo_sensor_f186fa_idx'),
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['timestamp'], name='core_datapo_timesta_9ad9a4_idx'),
        ),
    ]
