# Generated by Django 5.1.3 on 2025-01-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='l',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='r',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='t',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
