# Generated by Django 5.1.3 on 2025-01-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sensordata_l_sensordata_r_sensordata_s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataLegacy',
            fields=[
            ],
            options={
                'verbose_name': 'Legacy Sensor Data (t & h)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sensordata',),
        ),
    ]
