# Generated by Django 5.1.3 on 2025-01-30 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sensordatalegacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=1)),
                ('value', models.FloatField()),
            ],
        ),
    ]
