services:
  db:
    image: timescale/timescaledb:2.11.1-pg14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: nombre_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapp:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    env_file:
      - ../.env
    volumes:
      - ../:/app
      - static_volume:/app/static
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - webapp

volumes:
  static_volume:
  postgres_data:
