services:
  db:
    image: timescale/timescaledb:2.11.1-pg14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: kodex_user
      POSTGRES_PASSWORD: kodex_pass_do_not_use_in_production
      POSTGRES_DB: dj_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapp:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - db
      - nginx
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --noinput --clear &&
             gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ../static:/static
      - ../media:/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro   
    ports:
      - "80:80"

volumes:
  static_volume:
  postgres_data:
