# use false for development (x86) and true for production (raspberry pi)
arm: true
 
raspberry_id: "rpi4"
 
# api_urls: list of endpoints to send data to
api_urls:
  - "http://localhost:8000/api/data-point/"
  # - "http://another-endpoint.com/api/data-point/"
 
# implemented hardware_type: dht22, dht11, mcp3008, fake
# dht22 and dht11 params: gpio (int)
# mcp3008 params: channel (int), min_v (float) <- used for calibration
# implemented metrics: t (temperature), h (humidity), s (soil moisture), l (light)
sensors:
  - name: "vege-oeste"
    hardware_type: "dht22"
    interval: 10
    params:
      - gpio: 4
    metrics: ["t", "h"]
 
  - name: "vege-este"
    hardware_type: "dht22"
    interval: 10
    params:
      - gpio: 22
    metrics: ["t", "h"]
 
  - name: "subs-1"
    hardware_type: "mcp3008"
    interval: 5
    params:
      - channel: 0
      - min_v: 1.68
    metrics: ["s"]
 
  - name: "subs-2"
    hardware_type: "mcp3008"
    interval: 5
    params:
      - channel: 1
      - min_v: 1.67
    metrics: ["s"]
 
  - name: "subs-3"
    hardware_type: "mcp3008"
    interval: 5
    params:
      - channel: 2
      - min_v: 1.50
    metrics: ["s"]
 
  - name: "ldr-1"
    hardware_type: "mcp3008"
    interval: 5
    params:
      - channel: 7
      - min_v: 0.5
    metrics: ["l"]