# Indica si estamos en una Raspberry Pi (ARM)
arm: false

# Identificación del dispositivo
raspberry_id: "rpi1"

# URLs de las APIs
api_urls:
  # - "https://kcbd.grupoalvs.com/api/sensor-data/"
  # - "https://kcbd-monitor.grupoalvs.com/api/sensor-data/"
  - "http://localhost:8000/api/data-point/"

# Configuración de sensores
sensors:
  - name: "greenhouse-1"
    hardware_type: "fake"
    interval: 10
    param: 4
    metrics: ["t", "h"]

  - name: "greenhouse-2"
    hardware_type: "fake"
    interval: 10
    param: 22
    metrics: ["t", "h"]

  - name: "soil-1"
    hardware_type: "fake"
    interval: 5
    param: 0
    metrics: ["s"]

  - name: "soil-2"
    hardware_type: "fake"
    interval: 5
    param: 1
    metrics: ["s"]

  - name: "light-1"
    hardware_type: "fake"
    interval: 5
    param: 2
    metrics: ["l"]

  # Ejemplo de sensor DHT (temperatura y humedad)
  # - name: nombre único del sensor
  # - hardware_type: "dht11" o "dht22"
  # - interval: tiempo entre lecturas en segundos
  # - param: número del pin GPIO (sin el 'D')
  # - metrics: métricas que reporta ["t" y/o "h"]
  #
  # - name: "example-dht"
  #   hardware_type: "dht22"  # o "dht11"
  #   interval: 10
  #   param: 17      # conectado a GPIO17
  #   metrics: ["t", "h"]  # temperatura y humedad
